name: Python CI
on:
  push:
    branches: [ghcr]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Publish Docker Container
        uses: darthtrevino/github-container-registry-build-push@main
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: intelligence-toolkit:latest
          dockerfile-path: ./Dockerfile
          build-context: ./