name: Python CI
on:
  push:
    branches: [ghcr]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build the Docker image
          run: |
              docker build . -t ghcr.io/microsoft/intelligence-toolkit:latest
              docker push ghcr.io/microsoft/intelligence-toolkit:latest